CREATE TABLE "issued_credentials" (
	"id" uuid PRIMARY KEY NOT NULL,
	"config_id" varchar(128) NOT NULL,
	"format" varchar(32) NOT NULL,
	"holder_jkt" varchar(64),
	"status_idx" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "issued_credentials_status_idx_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"status" integer DEFAULT 0 NOT NULL,
	"issued_at" timestamp DEFAULT now() NOT NULL,
	"revoked_at" timestamp
);
