rootProject.name = "eudi-wallet-sdk"

include(":cbor")
include(":wallet-api")
include(":testkit")
include(":credential-store")
include(":sdjwt")
include(":openid4vci")
include(":openid4vp")
include(":trust")
include(":trustlist")
include(":mdoc")
include(":statuslist")
include(":txlog")
include(":proximity")
include(":wallet")
